### ISSUE TITLE
Failed to perform the action update

### ISSUE THREAD

**Issue by milandzuris** [beecho01/material-symbols#12]
**Describe the bug**
Failed to perform the action update/install. startswith first arg must be str or a tuple of str, not NoneType

**HA**
2024.10.3

**MS**
v1.0.0

**Comment by beecho01** [comment]
Have you attempted to update from v1.0.0 as a `Dashboard` repository or have you followed the [migration](https://github.com/beecho01/material-symbols#migrating-from-v1xx-to-202xxx) steps and installed as an `Integration` repository?
