### ISSUE TITLE
Installation guide wrong

### ISSUE THREAD

**Issue by Vikvoch** [beecho01/material-symbols#2]
Hello beecho01,
Your icon pack is awesome but you have the install guide in README.md wrong.
I was unable to add it through HACS. After a bit of tinkering I found out that after you add it to HACS and download it you need to add this into `configuration.yaml`
```
frontend:
  extra_module_url:
    - /local/community/material-symbols/material-symbols.js
```
Please fix it, so no one will spend half a day adding some icons to HA.

Thanks
Vikvoch

**Comment by beecho01** [comment]
Has now been resolved. Thanks for finding that issue.
