### ISSUE TITLE
Obslete Function Object.observe Used

### ISSUE THREAD

**Issue by Nerwyn** [beecho01/material-symbols#3]
**Describe the bug**
The following error can be seen in the browser console:

```
Uncaught TypeError: Object.observe is not a function
    at material-symbols.js?hacstag=669605185033:69398:8
```

**To Reproduce**
1. Install Material Symbols via HACS
2. Open the browser console and refresh the page. Note the error message.

**Expected behavior**
No errors should be logged on material symbols load. Symbols should appear when used on chromium browsers and be available to select via the icon picker.

**Screenshots**
![image](https://github.com/beecho01/material-symbols/assets/43071698/4e6cae88-c4a4-42e0-8d67-bf887ffb57b9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (chromium fork), Edge (also a chromium fork)
 - Version: 0.3.3

**Additional context**
`Object.observe(MATERIAL_SYMBOLS_MAP, handleSymbolsMapChange);` is called on line 69711. `Object.observe` has been deprecated since 2015 and obsoleted on chromium browsers. [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) should be used instead.

**Comment by beecho01** [comment]
Has now been resolved as per commit [756e7d8](https://github.com/beecho01/material-symbols/commit/756e7d8f2384bcf9c680499ac26580b9784822cb#diff-8d6b8bcf10cee6be4f619c67285680d63a5e8a08ad1db74f057316ef64ad788a)
