### ISSUE TITLE
Adding breaks custom cards

### ISSUE THREAD

**Issue by dgpapagian** [beecho01/material-symbols#4]
Steps:
Installing the repository using HACS (downloading and installing it)
Modify configuration.yaml with provided code
Restart HA

Issue:
All custom elements say error "Custom-element doesn't exist" in dashboards

**Comment by beecho01** [comment]
Hi @dgpapagian. I think there are a few things we can try:

1. Can you try clearing the browser cache for me and retesting?
2. Does this work in another browser?
3. Remove from resources section of the configuration.yaml:

	```
    - url: /hacsfiles/material-symbols/material-symbols.js
	   type: module
	```
	and add:
	```
	frontend:
	  extra_module_url:
	    - /local/community/material-symbols/material-symbols.js
	```
	Restart Home Assistant

Let me know if any of these help.

**Comment by keezppc** [comment]
I ran into this issue too but it was because I had added the repository but hadn't actually installed.  This isn't clearly stated in the install instructions

**Comment by mwilky** [comment]
> Hi @dgpapagian. I think there are a few things we can try:
> 
> 1. Can you try clearing the browser cache for me and retesting?
> 2. Does this work in another browser?
> 3. Remove from resources section of the configuration.yaml:
>    ```
>    - url: /hacsfiles/material-symbols/material-symbols.js
>       type: module
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    and add:
>    ```
>    frontend:
>      extra_module_url:
>        - /local/community/material-symbols/material-symbols.js
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Restart Home Assistant
> 
> Let me know if any of these help.

Clearing cache still same issue.

Making the change to configuration.yaml like you mentioned fixes the custom cards but your icons don't show then.

**Comment by beecho01** [comment]
Can you confirm the repository is installed via HACS, as I forgot to add these to the instructions. I have updated the instructions to show this: [https://github.com/beecho01/material-symbols#add-hacs-custom-repository](https://github.com/beecho01/material-symbols#add-hacs-custom-repository)

The files should be present in the folder location `config/www/community/material-symbols/material-symbols.js` once installed.

**Comment by dgpapagian** [comment]
The repo is correctly downloaded and installed through HACS. The issue appears when I modify the configuration.yaml (causing all custom cards to show error). If I follow the manual installation, no m3 icons show regardless what I try

**Comment by mwilky** [comment]
> Can you confirm the repository is installed via HACS, as I forgot to add these to the instructions. I have updated the instructions to show this: https://github.com/beecho01/material-symbols#add-hacs-custom-repository
> 
> The files should be present in the folder location `config/www/community/material-symbols/material-symbols.js` once installed.

Yep all installed correctly. Would be ideal if we didn't have to add the lovelace config to configuration.yaml as it means we will need to manually port over all the other resources we've had previously installed.

**Comment by dgpapagian** [comment]
I appear to have solved the problem (at least on my end), and I think it is because the README instructions are wrong and there isn't something else going on with the code per se.

I believe this part
```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/material-symbols/material-symbols.js
      type: module
```
should be replaced with 
```
frontend:
  extra_module_url:
    - /hacsfiles/material-symbols/material-symbols.js
```
as modifying lovelace to yaml mode causes all sorts of issues + needs the creation and reference of a `ui-lovelace.yaml` file as per [the official documentation](https://fonts.google.com/icons?icon.platform=android). Also I don't see any reason why it was different than the referenced [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons) project in the first place

Also, the provided test icon `m3s:switches-outlined` does not exist in the material-symbols.js, so I suggest to change it to one that exists like `m3s:volume-off-outlined`.

Lastly the provided directory is laggy and slow. I propose to direct users to copy the icons code from [google's official source](https://fonts.google.com/icons?icon.platform=android) until fixed (I know not all Google icons are present in the integration - example the switches one - but I think it is better for now). 

I have forked the project and proposed the changes.
