### ISSUE TITLE
Rounded versions of some window icons aren't using the rounded version of the icon

### ISSUE THREAD

**Issue by Fxsch** [beecho01/material-symbols#8]
**Describe the bug**
Affected icons are the following:
- m3s:window-closed-rounded-filled
- m3s:window-closed-rounded
- m3s:window-open-rounded-filled
- m3s:window-open-rounded
- m3s:window-sensor-rounded-filled
- m3s:window-sensor-rounded

**Screenshots**
Example with `m3s:window-closed-rounded-filled`:
![image](https://github.com/user-attachments/assets/0a6dc295-75df-47ec-92d5-df734e8ace6b)

What it's supposed to look like:
![image](https://github.com/user-attachments/assets/be337e81-ada5-4242-b5c5-83ed9b865cc6)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Browser: LibreWolf (Firefox fork)
 - Version: 129.0.2-1

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Android 13
 - Browser: Home Assistant app
 - Version: 2024.7.3-minimal

**Comment by beecho01** [comment]
I have done a major update to this and migrated from Lovelace/Dashboard repository, to an Integration repository. In this change I have also changed how I get the icons and where from. This has also changed the icon names now too.

If you wouldn't mind, please follow the steps in [Migrating from v1.X.X to 202X.X.X](https://github.com/beecho01/material-symbols#migrating-from-v1xx-to-202xxx) and then attempt install via [HACS Method 2](https://github.com/beecho01/material-symbols#hacs-method-2).

The icon reference will need to be changed from `m3s:window-closed-rounded-filled`, and should now be `m3rf:window-closed`

**Comment by Fxsch** [comment]
I tried that but I'm having an issue. The files are all there under `custom_components/material_symbols` but the icons don't show up at all. It's not just that they don't render but they don't even show up when I set an icon in the interface (All the icons get listed when you do that and they're not there). Just copy pasting the icon name didn't work either. I cleared my browser cache and restarted Home Assistant multiple times. I even tried restarting the whole Home Assistant container and I tried it in the Android app and Butler (which is a Linux app for Home Assistant).

**Comment by beecho01** [comment]
Sorry to hear this. Definitely not expected behaviour. I'd like to see if we can Identify where the issue might be.

You should be able to see it using something similar to this, `https://xxx.ui.nabu.casa/material_symbols/icons/outlined/10k.svg`. Can you see if can get this to load? If yes, this would suggest that the integration has installed and that the `__init__.py` is working as expected and exposing the image.

Are there any console logs in your browser? If you see the generated console graphic, similar to the image below, `material_symbols.js` has loaded. Are there any other console logs pertaining to `material_symbols.js`?

<img width="333" alt="image" src="https://github.com/user-attachments/assets/a3f2102f-33e6-4017-a859-0935e26b9053">
<br/>

**Comment by Fxsch** [comment]
I tried all the things you suggested and then I found out why it didn't work, my issue is fixed now.

It's actually a stupidly simple thing, I just didn't add the integration in the HA settings.  
The thing is, in the HACS Method 1, in the "Installation" section of the README, the second button is there to do that but you told me to use HACS Method 2 and that step is missing there, so I didn't know I had to do that. I can just quickly add that step to the README if you want me to tho. And thanks a lot for your help.

Funny thing is, the original reason why I opened this issue still persists.  
The icon finder now shows it correctly but in HA, the rounded version of the icons, I originally listed, are still not rounded.

**Comment by Fxsch** [comment]
### Here's also example screenshots of `window-open`
In HA:
![image](https://github.com/user-attachments/assets/ae6fb4b9-7c94-47ed-9cb1-1c502f9bcc48)

In the icon finder:
![image](https://github.com/user-attachments/assets/5296e110-6620-41cc-be5b-ef698518481f)

**Comment by beecho01** [comment]
I am unsure how this has happened as these should be automatically sorted. I shall see if I can refine that auto-sorting process to make sure this doesnt happen again.

I have deployed an updated in [2024.10.24](https://github.com/beecho01/material-symbols/releases/tag/2024.10.24) with a manual update to these icons.

**Comment by beecho01** [comment]
I have also updated the HACS Method 2 and Manual Installation in the README as per your observation.
